version: '3.8'

services:
  nginx:
    image: nginx:1.21.6
    container_name: unicorecms-nginx
    profiles: 
      - nginx
    restart: unless-stopped
    environment:
      - ADMIN_HOST=${HOST?err}
      - CLIENT_HOST=${CLIENT_HOST?err}
      - SERVER_HOST=${SERVER_HOST?err}
      - CLIENT_PORT=${CLIENT_PORT:-3000}
      - ADMIN_PORT=${ADMIN_PORT:-4000}
      - SERVER_PORT=${SERVER_PORT:-5000}
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./logs/nginx:/var/log/nginx
    ports:
      - 80:80
      - 443:443

  mariadb:
    image: "mariadb:10.8.2"
    container_name: unicorecms-mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE?err}
      MYSQL_USER: ${MYSQL_USER?err}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?err}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?err}
    volumes:
      - ./docker/mysql-data:/var/lib/mysql

  app:
    container_name: unicorecms
    profiles: 
      - prod
    restart: always
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: npm run dev
    volumes:
      - .:/usr/local/app
      - /usr/local/app/node_modules
      - /usr/local/app/workspaces/admin/node_modules
      - /usr/local/app/workspaces/client/node_modules
      - /usr/local/app/workspaces/common/node_modules
      - /usr/local/app/workspaces/server/node_modules
      - /usr/local/app/workspaces/admin/.nuxt
      - /usr/local/app/workspaces/client/.nuxt
      - /usr/local/app/workspaces/common/dist
      - /usr/local/app/workspaces/server/dist
    depends_on:
      - mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: unicorecms-pma
    restart: unless-stopped
    profiles: 
      - dev
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - 8081:80
