name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        mv .env.example .env
        npx lerna bootstrap
        npm run build

    - name: Prepare artifact
      run: |
        rm -rf **/node_modules
        rm -rf workspaces/client/.nuxt
        rm -rf workspaces/client/dist
        rm -rf /logs
        rm -rf **/yarn-error.log
        rm -rf **/package-lock.json
        rm -rf **/yarn.lock
        mv .env.example .env
    - uses: actions/upload-artifact@v3
      with:
        name: UnicoreCMS
        path: ./

