name: Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mv .env.example .env
        docker-compose --profile nginx --profile prod up
    - name: Test TypeORM
      run: docker exec -t -i unicorecms npm run sync
